Transform: 'AWS::Serverless-2016-10-31'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: src/app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Policies:
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
              - 's3:ObjectCreated:*'

  SourceImageBucket:
    Type: 'AWS::S3::Bucket'

