on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  aws_sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      
      - run: 'pip --disable-pip-version-check install awscli aws-sam-cli'

      - run: 'cp ".github/samconfig.toml" "AWS Lambdas/samconfig.toml"'
      
      - name: sam build
        working-directory: 'AWS Lambdas'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 'sam build'

      - name: sam deploy
        working-directory: 'AWS Lambdas'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 'sam deploy --no-fail-on-empty-changeset'
